### PR TITLE
Add new drum kits

### PR DESCRIPTION
**Pull request by GuiPassoskt**
Create new drum kits used by drummers like:
Dave Grohl (Nirvana)
Ian Paice (Deep Purple)
John Bonham (Led Zepplin)
Travis Barker (Blink 182)
Tre Cool (Green Day)

### CODE REVIEW

**Comment by theGreatWhiteShark** [comment]
Hey @GuiPassoskt,

Sounds great!

Did you created the samples yourself? If so, we could host them on our SourceForge account along with all the other kits.

**Comment by GuiPassoskt** [comment]
Hi

Yes I made the samples and drum kits myself, soon I will update my
repository with new kits.  I'm also a developer, but I'm front-end, I'm
happy to be able to help with something like that too.

Thanks

**Comment by theGreatWhiteShark** [comment]
> Yes I made the samples and drum kits myself, soon I will update my
repository with new kits

Awesome!

One thing I want to draw your attention to is the license you used for your kits. GPL is tailored for software and it is not entirely sure whether it is applicable to things like audio samples at all. In case you want your kit to have a copyleft license, I would recommend [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/). But this implicates that all music created with those kits has to be licensed under the same license and - among others - one must tolerate that people can sell the music without any royality. Other common licenses would be [CC BY](https://creativecommons.org/licenses/) or [CC0 / public domain](https://wiki.creativecommons.org/wiki/Public_domain). The benefit of using Creative Commons licenses is that they are widely used and known among artists and have clear implications regarding artistic work.

**Comment by theGreatWhiteShark** [comment]
>  I'm also a developer, but I'm front-end, I'm
happy to be able to help with something like that too.

Excellent!

For version 1.2.0 I tried to make frontend tweaking more accessible by exposing all/most colors in the Preferences and rewriting widget customization in a CSS-like way, like in the [Button](https://github.com/hydrogen-music/hydrogen/blob/master/src/gui/src/Widgets/Button.cpp) class. Maybe there are some easy wins you spot or are up to give the GUI itself a more modern look. (A lot of work was done on the "modern feel" side lately)

**Comment by GuiPassoskt** [comment]
> > Sim, eu mesmo fiz os samples e kits de bateria, em breve atualizarei meu 
> > repositório com novos kits
> 
> Incrível!
> 
> Uma coisa que quero chamar sua atenção é a licença que você usou para seus kits. A GPL é adaptada para software e não é totalmente certo se ela é aplicável a coisas como amostras de áudio. Caso você queira que seu kit tenha uma licença copyleft, eu recomendaria [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/) . Mas isso implica que toda a música criada com esses kits tem que ser licenciada sob a mesma licença e - entre outras - deve-se tolerar que as pessoas possam vender a música sem qualquer royalties. Outras licenças comuns seriam [CC BY](https://creativecommons.org/licenses/) ou [CC0/domínio público](https://wiki.creativecommons.org/wiki/Public_domain) . A vantagem de usar as licenças Creative Commons é que elas são amplamente utilizadas e conhecidas entre os artistas e têm implicações claras em relação ao trabalho artístico.

Right! I will adjust the license and send again

Thanks

**Comment by GuiPassoskt** [comment]
> > Sim, eu mesmo fiz os samples e kits de bateria, em breve atualizarei meu 
> > repositório com novos kits
> 
> Incrível!
> 
> Uma coisa que quero chamar sua atenção é a licença que você usou para seus kits. A GPL é adaptada para software e não é totalmente certo se ela é aplicável a coisas como amostras de áudio. Caso você queira que seu kit tenha uma licença copyleft, eu recomendaria [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/) . Mas isso implica que toda a música criada com esses kits tem que ser licenciada sob a mesma licença e - entre outras - deve-se tolerar que as pessoas possam vender a música sem qualquer royalties. Outras licenças comuns seriam [CC BY](https://creativecommons.org/licenses/) ou [CC0/domínio público](https://wiki.creativecommons.org/wiki/Public_domain) . A vantagem de usar as licenças Creative Commons é que elas são amplamente utilizadas e conhecidas entre os artistas e têm implicações claras em relação ao trabalho artístico.

Right! I will adjust the license and send again

Thanks

**Comment by GuiPassoskt** [comment]
Right! I will adjust the license and send again

Thanks

**Comment by GuiPassoskt** [comment]
Would the CC-BY license meet the requirements?

**Comment by theGreatWhiteShark** [comment]
> Would the CC-BY license meet the requirements?

CC-BY is totally fine. But any license allowing us to host and distribute the kit is fine. This is totally up to you. I just wanted to point out some licenses which are specially easy to work with from the artists perspective.

How about we add your kits to the existing ones at SourceForge? Putting the kits at some place the Hydrogen development team has access to would help big time to maintain Hydrogen and its ecosystem in the future. Would you be ok with that?

P.S. Sorry for the late reply. Lot's of work/family stuff.

**Comment by GuiPassoskt** [comment]
> > Would the CC-BY license meet the requirements?
> 
> CC-BY is totally fine. But any license allowing us to host and distribute the kit is fine. This is totally up to you. I just wanted to point out some licenses which are specially easy to work with from the artists perspective.
> 
> How about we add your kits to the existing ones at SourceForge? Putting the kits at some place the Hydrogen development team has access to would help big time to maintain Hydrogen and its ecosystem in the future. Would you be ok with that?
> 
> P.S. Sorry for the late reply. Lot's of work/family stuff.

Alright, you can add yes without problems, soon I will make other kits available thanks!

**Comment by GuiPassoskt** [comment]
Sorry, I wasn't supposed to close the pull request

**Comment by GuiPassoskt** [comment]
You can add the kits to SourceForge

Thanks!

**Comment by theGreatWhiteShark** [comment]
I just took a look at your kits. Sounds nice. Thanks for you work!

I have one suggestion but it is entirely up to you whether you want to implement it.

In addition to using song and pattern editor Hydrogen can also be used as a pure drum synth. To do so, one connects a MIDI input, like edrum or MIDI keyboard, and Hydrogen will generate sounds for all incoming MIDI events. However, by itself Hydrogen does not know which instrument corresponds to which incoming note. The mapping is, instead, done on a per-drumkit basis in two different ways - which is switched by checking "Use output note as input" in Preferences > MIDI System. 

1. When unchecked, the first instrument in the instrument list is assumed to correspond to MIDI note key 36, the second 37, third 38, and so on. Mapping is done here according to the actual order of instruments.
2. When checked, the number set in the "Note" spin box in "MIDI Output" part of the instrument editor is used.

But which note is the *right one* for a particular instrument is a different story. Although lot's of it is vendor-specific, there is the so called [General MIDI](https://en.wikipedia.org/wiki/General_MIDI#Percussion) standard which is the most common one (and used by many Hydrogen users).

Complying with this standard in terms of instrument order is often impossible as it would be an antipattern to introduce dummy instruments solely for this purpose. But maybe you could adjust the note values in the instrument editors for the instruments of your kits to better match the ones in the standard. E.g. Dave Grohl kit > Snare > `midiOutNote` 37 => 38.

**Comment by theGreatWhiteShark** [comment]
And just a note: all the instruments of your kits have a single layer. That's totally fine. I just want to make sure you are aware that Hydrogen supports multiple layers/samples per instruments. Those will be selected per incoming velocity or using an adjustable selection algorithm in case multiple samples are present for the same velocity. Together with the humanization feature this is intended to give a more natural sound.

**Comment by GuiPassoskt** [comment]
> And just a note: all the instruments of your kits have a single layer. That's totally fine. I just want to make sure you are aware that Hydrogen supports multiple layers/samples per instruments. Those will be selected per incoming velocity or using an adjustable selection algorithm in case multiple samples are present for the same velocity. Together with the humanization feature this is intended to give a more natural sound.

I'll tweak the kits with the midi notes and as soon as it's all right, I'll let you know. 
P.S. Sorry for the late reply. Lot's of work and family stuff.

**Comment by GuiPassoskt** [comment]
I updated the kits with the midi notes, the kits will have only one layer of sounds, I followed the general midi pattern to configure the notes, I think I can now include them in the source forge directory

Thanks!

**Comment by theGreatWhiteShark** [comment]
> I updated the kits with the midi notes

Hey. Is https://github.com/GuiPassoskt/hydrogen-drumkits/commit/d8dafc5a8166e228bce9962886c288228e3821a7 the latest update you are referring to? When diffing the kits on this commit with the original one I just see changes in the license and in the author string in the Dave Grohl kit. Is this correct?

**Comment by GuiPassoskt** [comment]
> > I updated the kits with the midi notes
> 
> Hey. Is [GuiPassoskt/hydrogen-drumkits@d8dafc5](https://github.com/GuiPassoskt/hydrogen-drumkits/commit/d8dafc5a8166e228bce9962886c288228e3821a7) the latest update you are referring to? When diffing the kits on this commit with the original one I just see changes in the license and in the author string in the Dave Grohl kit. Is this correct?

It really looks like I didn't save the changes, I'll tweak and update the kits again

**Comment by GuiPassoskt** [comment]
That's it, the kits are already updated, only updates were made to the midi notes of the kits

Thanks

**Comment by theGreatWhiteShark** [comment]
> That's it, the kits are already updated, only updates were made to the midi notes of the kits

Awesome! I uploaded your kits.

There is still one thing about your code changes in this PR: you seemed to autoformat the whole drumkit_list.php file. Could you, instead, just add the lines corresponding to your kit? This will keep the change set more concise.

If you want I can do this too. But I don't want to mess with your changes without asking first.

**Comment by GuiPassoskt** [comment]
> > That's it, the kits are already updated, only updates were made to the midi notes of the kits
> 
> Awesome! I uploaded your kits.
> 
> There is still one thing about your code changes in this PR: you seemed to autoformat the whole drumkit_list.php file. Could you, instead, just add the lines corresponding to your kit? This will keep the change set more concise.
> 
> If you want I can do this too. But I don't want to mess with your changes without asking first.

It's ok, I can adjust here

Thanks

**Comment by GuiPassoskt** [comment]
I've already undone the formatting and updated the kits' links to source forge

**Review by theGreatWhiteShark — APPROVED** [review]

**Pull request merged**
