### PR TITLE
Addsing a quesiton about interplay between H2+Anaconda

### PR DESCRIPTION
**Pull request by theGreatWhiteShark**
Based on issue #625 of the Hydrogen package I would suggest to add a question about how to compile Hydrogen with Anaconda present. This will replace the tweaks of the CMakeFile.txt in pull request #624.

### CODE REVIEW

**Comment by trebmuh** [comment]
_([see here](https://github.com/hydrogen-music/hydrogen/issues/625))_

**Comment by bratner** [comment]
@theGreatWhiteShark just playing the devil advocate here with a comment. What you wrote in the FAQ is not strictly true.
```cmake``` does not look for libraries on PATH. ```cmake``` runs utilities which in their turn report library paths. Anacondas' utilities take precedence and report non-standard paths for QT distribution.
I can't currently think on how to translate this to a FAQ type language but I will think of something eventually.

P.S: The fact that Anaconda brings it's own full-blown QT which is compiled against anaconda's own library directories, maybe should be mentioned.

**Comment by theGreatWhiteShark** [comment]
I did not wrote that `cmake` is looking for libraries in `$PATH` but in the "system files". It's as imprecise as possible but I don't think people, who are having a look at the FAQ, are interested in learning something about the Linux system. Adding more variables or the order and locations of the folders searched by `cmake` will probably just scare some beginners of. 

But your right, mentioning Qt is a good idea. I've added it.

**Comment by mauser** [comment]
Thanks, added!

**Pull request merged**
